# Generated by Django 3.1 on 2023-05-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20230520_1032'),
        ('orden', '0002_auto_20230518_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_orden', to='orden.orden'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_productos', to='producto.producto'),
        ),
    ]
